#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/nginx
PID_FILE=/run/nginx/nginx.pid
CONFIG_FILE=/etc/nginx/nginx.conf
NAME=nginx

test_nginx_config() {  
    if $DAEMON -t -c $CONFIG_FILE >/dev/null 2>&1; then
        return 0
    else
        $DAEMON -t -c $CONFIG_FILE
        return $?
    fi  
}  
if [ ! -d /run/nginx/ ]; then
    mkdir -p /run/nginx/
fi

case "$1" in
    start)
        if [ -e "$PID_FILE" ]; then
            echo "$NAME" is running, pid="$(cat $PID_FILE)"
            exit 1
        else
            echo "Starting $NAME"
            test_nginx_config
            start-stop-daemon --start --quiet --exec $DAEMON -- -c $CONFIG_FILE || true
            echo "$NAME"
        fi
        ;;
    stop)
        echo "Stopping $NAME"
        start-stop-daemon --stop --quiet --pidfile $PID_FILE || true
        echo "$NAME"
        ;;
    restart|force-reload)
        echo "Restarting $NAME"
        start-stop-daemon --stop --quiet --pidfile $PID_FILE || true
        sleep 1
        test_nginx_config
        start-stop-daemon --start --quiet --exec $DAEMON -- -c $CONFIG_FILE || true
        echo "$NAME"
        ;;
    reload)
        echo "Reloading $NAME configuration"
        test_nginx_config
        start-stop-daemon --signal HUP --quiet --pidfile $PID_FILE || true
        echo "$NAME"
        ;;
    configtest|testconfig)
        echo "Testing $NAME configuration"
        if test_nginx_config; then
            echo "$NAME"
        else
            exit $?
        fi
        ;;
    pid)
        if [ -e "$PID_FILE" ]; then
            cat $PID_FILE
        fi
        ;;
    *)
        echo "Usage: $NAME {start|stop|restart|reload|force-reload|configtest|pid}" >&2
        exit 1
        ;;
esac
exit 0